api_platform:
  title: Relentless
  version: 1.0.0

  defaults:
    stateless: true
    # Default cache headers to control client and proxy caching
    cache_headers:
      vary: [ 'Content-Type', 'Authorization', 'Origin' ]

  # The list of supported request content-types
  formats:
    jsonld: [ 'application/ld+json' ]
    json: [ 'application/json' ]