framework:
  secret: '%env(APP_SECRET)%'

  session:
    enabled: false

when@test:
  framework:
    test: true
    session:
      # The test client requires a session handler to exist. This mock handler
      # is stateless and fast, ensuring tests don't affect each other.
      storage_factory_id: session.storage.factory.mock_file