parameters:
  app.graphql_introspection_enabled: '%env(bool:GRAPHQL_ENABLE_INTROSPECTION)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
