parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true
    bind:
      $mailerFrom: '%env(MAILER_FROM)%'
      $refreshTokenTtl: '%gesdinet_jwt_refresh_token.ttl%'

  App\:
    resource: '../src/'
